title: "de[v]blog"
url: "https://kyiimn.github.io"
baseurl: "/blog"
date_format: "%Y-%m-%d %H:%M"
search: true
show_dir_listing: false

social:
  name: Kim Yin
  links:
    - https://github.com/kyiimn
    - https://facebook.com/kyiimn
    - https://www.linkedin.com/in/%EC%9D%B8-%EA%B9%80-9ab62767/
    - https://instagram.com/kyiimn

locale: ko_KR
author: Kim Yin <kyiimn@gmail.com>
description: 개발을 하며 겪은 여러가지 일이나 자료에 대해 기록하고 있다.

timezone: Asia/Seoul

jekyll_timeago:
  depth: 1

comments:
  provider: "disqus"
  disqus:
    shortname: "kyiimn-github-io"

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: 'post'
      comments: true
      share: true
      tagline: true

permalink: /posts/:year/:title:output_ext

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

pagination:
  enabled: true
  debug: true
  per_page: 8
  permalink: /:num/
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    tag: '/tag/:name/'
    category: '/category/:name/'

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-V1JWDPTD45"
    anonymize_ip: false

exclude:
  - LICENSE
  - README.md
  - backup
